In [1]:
import numpy as np

In [3]:
array = np.array([[1,2,3],
                [3,4,6],
                [4,4,5]])
array

array([[1, 2, 3],
       [3, 4, 6],
       [4, 4, 5]])

In [4]:
array.ndim#维度

2

In [5]:
array.shape#形状

(3, 3)

In [6]:
array.size#元素的个数

9

In [7]:
array.dtype#元素类型

dtype('int32')

In [8]:
a = np.array([1,2,3],dtype=np.int32)
a

array([1, 2, 3])

In [9]:
a.dtype

dtype('int32')

In [13]:
b = np.array([1,2,3],dtype=np.float)
b.dtype

dtype('float64')

In [14]:
c = np.array([1,2,3])
c

array([1, 2, 3])

In [15]:
d = np.array([[1,2,3],
              [3,4,5]])
d

array([[1, 2, 3],
       [3, 4, 5]])

In [16]:
d.reshape((3,2))
d

array([[1, 2, 3],
       [3, 4, 5]])

In [17]:
d = d.reshape((3,2))

In [18]:
d

array([[1, 2],
       [3, 3],
       [4, 5]])

In [19]:
zero = np.zeros((3,3))
zero

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
zero = np.zeros((3,3),dtype=np.int32)

In [21]:
zero

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [22]:
one = np.ones((3,2))
one

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [23]:
empty = np.empty((3,2))
empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [24]:
e = np.arange(12)
e

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [25]:
e = e.reshape((2,6))
e

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [26]:
arr1 = np.array([[1,2,3],
                [3,4,5]])
arr2 = np.array([[1,1,1],
                [2,3,4]])
arr1 + arr2#按位运算

array([[2, 3, 4],
       [5, 7, 9]])

In [27]:
arr1 - arr2

array([[0, 1, 2],
       [1, 1, 1]])

In [28]:
arr1 * arr2

array([[ 1,  2,  3],
       [ 6, 12, 20]])

In [29]:
arr1 ** arr2#幂运算

array([[  1,   2,   3],
       [  9,  64, 625]], dtype=int32)

In [30]:
arr1 / arr2

array([[1.        , 2.        , 3.        ],
       [1.5       , 1.33333333, 1.25      ]])

In [31]:
arr1 % arr2

array([[0, 0, 0],
       [1, 1, 1]], dtype=int32)

In [32]:
arr1 // arr2#除法且取整

array([[1, 2, 3],
       [1, 1, 1]], dtype=int32)

In [33]:
arr1 * 10

array([[10, 20, 30],
       [30, 40, 50]])

In [34]:
arr2 + 2


array([[3, 3, 3],
       [4, 5, 6]])

In [35]:
arr3 = arr1 > 3

In [36]:
arr3

array([[False, False, False],
       [False,  True,  True]])

In [37]:
arr1[arr1>3]

array([4, 5])

In [38]:
arr1[~arr1>3]

array([], dtype=int32)

In [40]:
arr1[~(arr2>3)]

array([1, 2, 3, 3, 4])

In [44]:

arr2 = arr2.reshape((3,2))


In [45]:
np.dot(arr1, arr2)#矩阵乘法运算

array([[12, 17],
       [22, 31]])

In [46]:
arr1.dot(arr2#同上

array([[12, 17],
       [22, 31]])

In [47]:
arr1.T#矩阵转置

array([[1, 3],
       [2, 4],
       [3, 5]])

In [48]:
arr1

array([[1, 2, 3],
       [3, 4, 5]])

In [49]:
np.transpose(arr1)#矩阵的转置

array([[1, 3],
       [2, 4],
       [3, 5]])

In [50]:
sample = np.random.random((3,2))#生成3行2列从0到1的随机数
sample

array([[0.80010359, 0.20775063],
       [0.15313185, 0.2023761 ],
       [0.93622034, 0.96103522]])

In [56]:
sample1 = np.random.normal(size=(3,2))#生成3行2列符合标准正态分布的随机数
sample1

array([[ 0.87807646,  0.27333017],
       [-1.29587159,  1.18524082],
       [-1.06982545, -1.54492839]])

In [57]:
sample2 = np.random.randint(0, 10, size=(3,2))#生成3行2列从0到10的随机整数
sample2

array([[4, 1],
       [5, 0],
       [3, 0]])

In [58]:
np.sum(sample1)#求和

-1.5739779842207995

In [60]:
np.min(sample1)#最小值

-1.5449283910857223

In [61]:
np.max(sample2)#最大值

5

In [62]:
np.sum(sample2, axis=0)#对列求和

array([12,  1])

In [65]:
np.sum(sample2, axis=1)#对行求和

array([5, 5, 3])

In [66]:
np.argmin(sample2)#首个最小值的索引

3

In [67]:
np.mean(sample)#求平均值

4.333333333333333

In [68]:
sample.mean()#同上

4.333333333333333

In [70]:
np.median(sample)#中位数

5.0

In [71]:
np.sqrt(sample)#开方

array([[0.        , 2.82842712],
       [0.        , 2.23606798],
       [2.82842712, 2.23606798]])

In [76]:
sample4 = np.random.randint(0, 10, size=(1,10))
sample4

array([[0, 1, 7, 4, 8, 2, 9, 7, 6, 3]])

In [77]:
np.sort(sample4)#排序

array([[0, 1, 2, 3, 4, 6, 7, 7, 8, 9]])

In [81]:
np.sort(sample2)#对每一行排序

array([[1, 4],
       [0, 5],
       [0, 3]])

In [82]:
np.clip(sample4,2,7)#元素小于2变成2，元素大于7变成7

array([[2, 2, 7, 4, 7, 2, 7, 7, 6, 3]])

In [83]:
arr1 = np.arange(2,14)
arr1

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [84]:
arr1[2]#

4

In [85]:
arr1[2:4]#前闭后开

array([4, 5])

In [86]:
arr1[2:-1]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [87]:
arr1[:5]#前5个数据

array([2, 3, 4, 5, 6])

In [88]:
arr1[-2:]

array([12, 13])

In [89]:
arr2 = arr1.reshape(3,4)
arr2

array([[ 2,  3,  4,  5],
       [ 6,  7,  8,  9],
       [10, 11, 12, 13]])

In [90]:
arr2[1]#对行取值，去第一行

array([6, 7, 8, 9])

In [91]:
arr2[1,1]

7

In [92]:
arr2[1:2,1:2]

array([[7]])

In [94]:
for i in arr2:#迭代的行
    print(i)

[2 3 4 5]
[6 7 8 9]
[10 11 12 13]


In [95]:
for i in arr2.T:#迭代列
    print(i)

[ 2  6 10]
[ 3  7 11]
[ 4  8 12]
[ 5  9 13]


In [96]:
for i in arr2.flat:#迭代元素
    print(i)

2
3
4
5
6
7
8
9
10
11
12
13


In [97]:
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
arr3 = np.vstack((arr1,arr2))#垂直合并
arr3

array([[1, 2, 3],
       [4, 5, 6]])

In [98]:
arr4 = np.hstack((arr1, arr2))#水平合并
arr4

array([1, 2, 3, 4, 5, 6])

In [102]:
arr5 = np.vstack((arr1,arr1,arr2))
arr5

array([[1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [103]:
arr6 = np.concatenate((arr1,arr2,arr1))
arr6

array([1, 2, 3, 4, 5, 6, 1, 2, 3])

In [110]:
arr7 = np.concatenate((arr3,arr5),axis=0)#纵向合并
arr7

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [1, 2, 3],
       [4, 5, 6]])

In [112]:
arr8 = np.concatenate((arr3,arr3),axis=1)#横向合并
arr8

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [113]:
arr1.T#一维的array不能转置

array([1, 2, 3])

In [114]:
arr1

array([1, 2, 3])

In [115]:
arr1.shape

(3,)

In [116]:
arr1_1 = arr1[np.newaxis, :]#增加维度
arr1_1

array([[1, 2, 3]])

In [117]:
arr1_1.T

array([[1],
       [2],
       [3]])

In [118]:
arr1_1.ndim

2

In [119]:
arr1_1.shape

(1, 3)

In [120]:
arr1_2 = arr1[:,np.newaxis]
arr1_2

array([[1],
       [2],
       [3]])

In [121]:
arr1_2.shape

(3, 1)

In [122]:
arr1_3 = np.atleast_2d(arr1)#如果是二维则不做改变；如果是一维则将其变成二维
arr1_3

array([[1, 2, 3]])

In [123]:
arr1 = np.arange(12).reshape((3,4))
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [124]:
arr2, arr3 = np.split(arr1, 2, axis=1)#水平方向分割，分成两个部分

In [125]:
arr2

array([[0, 1],
       [4, 5],
       [8, 9]])

In [126]:
arr3

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [129]:
arr1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
arr4, arr5, arr6 = np.split(arr1, 3, axis=0)

In [131]:
arr4

array([[0, 1, 2, 3]])

In [132]:
arr5

array([[4, 5, 6, 7]])

In [133]:
arr6

array([[ 8,  9, 10, 11]])

In [135]:
arr7, arr8, arr9 = np.array_split(arr1, 3, axis=1)#水平方向分割，分成3份，不等分割

In [136]:
arr7

array([[0, 1],
       [4, 5],
       [8, 9]])

In [137]:
arr8

array([[ 2],
       [ 6],
       [10]])

In [138]:
arr9

array([[ 3],
       [ 7],
       [11]])

In [139]:
arrv1, arrv2, arrv3 = np.vsplit(arr1, 3)#水平分割

In [140]:
arrv1

array([[0, 1, 2, 3]])

In [141]:
arrv2

array([[4, 5, 6, 7]])

In [142]:
arrv3

array([[ 8,  9, 10, 11]])

In [143]:
arrh1, arrh2 = np.hsplit(arr1, 2)#垂直分割

In [144]:
arrh1

array([[0, 1],
       [4, 5],
       [8, 9]])

In [145]:
arrh2

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [146]:
arr1 = np.array([1,2,3])

In [147]:
arr1

array([1, 2, 3])

In [148]:
arr2 = arr1#共享一块内存，换了个名字。浅拷贝

In [149]:
arr2

array([1, 2, 3])

In [150]:
arr2[0] = 5
arr2

array([5, 2, 3])

In [151]:
arr1

array([5, 2, 3])

In [152]:
arr3 = arr1.copy()#深拷贝，改变arr3不会改变arr1
arr3[1] = 12
arr3

array([ 5, 12,  3])

In [153]:
arr1

array([5, 2, 3])